services:
    web_server:
        container_name: web_server
        build: Docker/web_server
        ports:
            - '8080:80'
        volumes:
            - './:/var/www/html'
    db_server:
        container_name: db_server
        build: Docker/db_server
        ports:
            - '3306:3306'
        environment:
            MARIADB_ROOT_USER: 'root'
            MARIADB_ROOT_PASSWORD: 'test'